execute positioned ~~~ run function harvester
execute positioned ~~~1 run function harvester
execute positioned ~1~~ run function harvester
execute positioned ~1~~1 run function harvester
execute positioned ~-1~~ run function harvester
execute positioned ~~~-1 run function harvester
execute positioned ~-1~~-1 run function harvester
execute positioned ~1~~-1 run function harvester
execute positioned ~-1~~1 run function harvester