export const ToolTags = [
    'minecraft:axe',
    'minecraft:axe',
    'minecraft:is_sword',
    'minecraft:is_shovel',
    'minecraft:is_pickaxe',
];
export const AutoSmeltRawOres = {
    "minecraft:raw_iron": "minecraft:iron_ingot",
    "minecraft:raw_gold": "minecraft:gold_ingot",
    "minecraft:raw_copper": "minecraft:copper_ingot",
    "minecraft:ancient_debris": "minecraft:netherite_scrap",
};
export const WoodConvertions = {
    "minecraft:oak_log": "minecraft:charcoal",
    "minecraft:spruce_log": "minecraft:charcoal",
    "minecraft:birch_log": "minecraft:charcoal",
    "minecraft:acacia_log": "minecraft:charcoal",
    "minecraft:cherry_log": "minecraft:charcoal",
    "minecraft:dark_oak_log": "minecraft:charcoal",
    "minecraft:jungle_log": "minecraft:charcoal",
    "minecraft:mangrove_log": "minecraft:charcoal",
    "minecraft:oak_wood": "minecraft:charcoal",
    "minecraft:spruce_wood": "minecraft:charcoal",
    "minecraft:birch_wood": "minecraft:charcoal",
    "minecraft:acacia_wood": "minecraft:charcoal",
    "minecraft:cherry_wood": "minecraft:charcoal",
    "minecraft:mangrove_wood": "minecraft:charcoal",
    "minecraft:dark_oak_wood": "minecraft:charcoal",
    "minecraft:jungle_wood": "minecraft:charcoal",
    "minecraft:cobblestone": "minecraft:stone",
    "minecraft:stone": "minecraft:stone",
    "minecraft:netherrack": "minecraft:netherbrick",
    "minecraft:basalt": "minecraft:smooth_basalt",
    "minecraft:deepslate": "minecraft:deepslate",
    "minecraft:cobbled_deepslate": "minecraft:deepslate",
    "minecraft:raw_gold_block": "minecraft:gold_block",
    "minecraft:raw_iron_block": "minecraft:iron_block",
    "minecraft:raw_copper_block": "minecraft:copper_block",
    "minecraft:sponge": "minecraft:sponge",
};
export const SmeltedConversions = {
    "minecraft:sand": "minecraft:glass",
    "minecraft:iron_ore": "minecraft:iron_ingot",
    "minecraft:deepslate_iron_ore": "minecraft:iron_ingot",
    "minecraft:gold_ore": "minecraft:gold_ingot",
    "minecraft:deepslate_gold_ore": "minecraft:gold_ingot",
    "minecraft:copper_ore": "minecraft:copper_ingot",
    "minecraft:deepslate_copper_ore": "minecraft:copper_ingot",
    ...WoodConvertions,
};
