//Coded by L4ggcrafter/ned2z
import "./onPlaneDeath.js"
import "./camera.js"
import "./planeMain.js"
import "./player/main.js"
import "entitySpawn.js"
import "aircraftSettings.js"
import "./initialize.js"
import "./entityRemove.js"
import "./workbench/main.js"
import "./entityHit.js"
import "./debug.js"
import "./blockComponentRegistry.js"
import "./shootingSystem/main.js"
import "./projectile/onHit.js"
import "./speedControl.js"
//import "./TEST.js"
//import "./plane/main.js"