setblock ~~~ air destroy
execute if block ~1 ~ ~ deepslate_iron_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_iron_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_iron_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_iron_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_iron_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_iron_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ deepslate_gold_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_gold_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_gold_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_gold_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_gold_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_gold_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ deepslate_redstone_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_redstone_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_redstone_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_redstone_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_redstone_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_redstone_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ deepslate_emerald_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_emerald_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_emerald_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_emerald_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_emerald_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_emerald_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ deepslate_lapis_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_lapis_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_lapis_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_lapis_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_lapis_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_lapis_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ deepslate_diamond_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_diamond_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_diamond_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_diamond_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_diamond_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_diamond_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ deepslate_coal_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_coal_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_coal_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_coal_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_coal_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_coal_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ deepslate_copper_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ deepslate_copper_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ deepslate_copper_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ deepslate_copper_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 deepslate_copper_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 deepslate_copper_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ iron_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ iron_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ iron_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ iron_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 iron_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 iron_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ gold_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ gold_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ gold_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ gold_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 gold_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 gold_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ redstone_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ redstone_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ redstone_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ redstone_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 redstone_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 redstone_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ emerald_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ emerald_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ emerald_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ emerald_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 emerald_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 emerald_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ lapis_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ lapis_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ lapis_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ lapis_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 lapis_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 lapis_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ diamond_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ diamond_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ diamond_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ diamond_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 diamond_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 diamond_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ coal_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ coal_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ coal_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ coal_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 coal_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 coal_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ copper_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ copper_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ copper_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ copper_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 copper_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 copper_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ quartz_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ quartz_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ quartz_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ quartz_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 quartz_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 quartz_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ ancient_debris positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ ancient_debris positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ ancient_debris positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ ancient_debris positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 ancient_debris positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 ancient_debris positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ nether_gold_ore positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ nether_gold_ore positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ nether_gold_ore positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ nether_gold_ore positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 nether_gold_ore positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 nether_gold_ore positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ stone["stone_type"="andesite"] positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ stone["stone_type"="andesite"] positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ stone["stone_type"="andesite"] positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ stone["stone_type"="andesite"] positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 stone["stone_type"="andesite"] positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 stone["stone_type"="andesite"] positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ stone["stone_type"="granite"] positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ stone["stone_type"="granite"] positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ stone["stone_type"="granite"] positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ stone["stone_type"="granite"] positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 stone["stone_type"="granite"] positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 stone["stone_type"="granite"] positioned ~ ~ ~-1 run function tools/veinminer
execute if block ~1 ~ ~ stone["stone_type"="diorite"] positioned ~1 ~ ~ run function tools/veinminer
execute if block ~-1 ~ ~ stone["stone_type"="diorite"] positioned ~-1 ~ ~ run function tools/veinminer
execute if block ~ ~1 ~ stone["stone_type"="diorite"] positioned ~ ~1 ~ run function tools/veinminer
execute if block ~ ~-1 ~ stone["stone_type"="diorite"] positioned ~ ~-1 ~ run function tools/veinminer
execute if block ~ ~ ~1 stone["stone_type"="diorite"] positioned ~ ~ ~1 run function tools/veinminer
execute if block ~ ~ ~-1 stone["stone_type"="diorite"] positioned ~ ~ ~-1 run function tools/veinminer